export const themeSections = [
  {
    id: "header",
    label: "الهيدر",
    titleKey: "homeHeaderTitle",
    descKey: "homeHeaderSubtitle",
    imageKey: "homeHeaderImage",
    headerExtra: true,
  },
  {
    id: "pages",
    label: "الصفحات",
    titleKey: "homePagesTitle",
    descKey: "",
    imageKey: "",
    pagesExtra: true,
  },
  {
    id: "hero",
    label: "الهيرو",
    titleKey: "homeHeroTitle",
    descKey: "homeHeroDesc",
    imageKey: "homeHeroImage",
    buttonKey: "homeHeroButton",
    heroExtra: true,
  },
  {
    id: "plants",
    label: "أقسام النباتات",
    titleKey: "homePlantSectionsTitle",
    descKey: "homePlantSectionsDesc",
    imageKey: "homePlantSectionsImage",
  },
  {
    id: "care",
    label: "شريط العناية",
    titleKey: "homeCareTitle",
    descKey: "homeCareDesc",
    imageKey: "homeCareImage",
  },
  {
    id: "offer",
    label: "بنر العروض",
    titleKey: "homeOfferTitle",
    descKey: "homeOfferDesc",
    imageKey: "homeOfferImage",
  },
  {
    id: "products",
    label: "المنتجات",
    titleKey: "homeProductsTitle",
    descKey: "homeProductsDesc",
    imageKey: "",
  },
  {
    id: "features",
    label: "مزايا المتجر",
    titleKey: "homeFeaturesTitle",
    descKey: "homeFeaturesDesc",
    imageKey: "",
  },
  {
    id: "footer",
    label: "الفوتر",
    titleKey: "footerTitle",
    descKey: "footerDescription",
    imageKey: "",
    footerExtra: true,
  },
];
